# Generated by Django 2.2 on 2021-03-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210319_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email_address',
            field=models.CharField(max_length=45),
        ),
    ]
