# Generated by Django 2.2 on 2021-03-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210320_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
